#!/usr/bin/env bash
set -euo pipefail

if [[ $# -gt 1 ]]; then
  echo "Usage: $(basename "$0") [<commit-message-file>]" >&2
  exit 1
fi

if [[ $# -eq 1 ]]; then
  if [[ -f "$1" ]]; then
    message="$(cat "$1")"
  else
    message="$1"
  fi
else
  message="$(cat)"
fi

subject="$(
  printf '%s\n' "$message" \
    | sed '/^#/d' \
    | sed '/^[[:space:]]*$/d' \
    | head -n 1 \
    | tr -d '\r'
)"

if [[ -z "$subject" ]]; then
  echo "commit-lint: commit subject is empty." >&2
  exit 1
fi

# Allow merge commits generated by Git tooling.
if [[ "$subject" =~ ^Merge[[:space:]] ]]; then
  exit 0
fi

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._/-]+\))?(!)?: .+$'

if ! printf '%s\n' "$subject" | grep -Eq "$pattern"; then
  echo "commit-lint: invalid commit subject:" >&2
  echo "  $subject" >&2
  echo >&2
  echo "Expected Conventional Commits format, for example:" >&2
  echo "  feat(ssh): support password authentication" >&2
  echo "  fix(ui): disable connect button while connecting" >&2
  exit 1
fi
